### ISSUE TITLE
App crash - possibly related to AgendaDayFragment?

### ISSUE THREAD

**Issue by fetching** [Droidcon-Boston/conference-app-android#164]
I deployed the app on to my Samsung Galaxy J7 phone via Android Studio.  The app has crashed twice and I found many of these stack traces written to my Android Studio Logcat with an "Unexpected EOF!"

Perhaps these traces are related?  You might get crash reports to correlate to these stack traces.

```
2019-03-20 23:12:39.547 11299-11299/com.mentalmachines.droidcon_boston E/AndroidRuntime:     at com.mentalmachines.droidcon_boston.views.agenda.AgendaDayFragment$addFloatingAnimation$1.onAnimationEnd(AgendaDayFragment.kt:243)
        at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:829)
        at android.animation.AnimatorSet.-wrap1(AnimatorSet.java)
        at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:784)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1153)
        at android.animation.ValueAnimator.cancel(ValueAnimator.java:1043)
        at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:983)
        at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:615)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1007)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1014)
        at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
        at android.animation.AnimatorSet.start(AnimatorSet.java:678)
        at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:807)
        at android.animation.AnimatorSet.-wrap1(AnimatorSet.java)
        at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:784)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1153)
        at android.animation.ValueAnimator.cancel(ValueAnimator.java:1043)
        at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:983)
        at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:615)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1007)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1014)
        at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
        at android.animation.AnimatorSet.start(AnimatorSet.java:678)
        at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:807)
        at android.animation.AnimatorSet.start(AnimatorSet.java:640)
        at com.mentalmachines.droidcon_boston.views.agenda.AgendaDayFragment$addFloatingAnimation$1.onAnimationEnd(AgendaDayFragment.kt:243)
        at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:829)
        at android.animation.AnimatorSet.-wrap1(AnimatorSet.java)
        at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:784)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1153)
        at android.animation.ValueAnimator.cancel(ValueAnimator.java:1043)
        at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:983)
        at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:615)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1007)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1014)
        at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
        at android.animation.AnimatorSet.start(AnimatorSet.java:678)
        at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:807)
        at android.animation.AnimatorSet.-wrap1(AnimatorSet.java)
        at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:784)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1153)
        at android.animation.ValueAnimator.cancel(ValueAnimator.java:1043)
        at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:983)
        at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:615)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1007)
        at android.animation.ValueAnimator.start(ValueAnimator.java:1014)
        at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
        at android.animation.AnimatorSet.start(AnimatorSet.java:678)
        at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:807)
        at android.animation.AnimatorSet.start(AnimatorSet.java:640)
        at com.mentalmachines.droidcon_boston.views.agenda.AgendaDayFragment$addFloatingAnimation$1.onAnimationEnd(AgendaDayFragment.kt:243)
        at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:829)
        at android.animation.AnimatorSet.-wrap1(AnimatorSet.java)
    
    read: unexpected EOF!
```

**Comment by sagar-viradiya** [comment]
![Screenshot 2019-03-13 at 2 54 45 PM](https://user-images.githubusercontent.com/11586051/54940405-ab370b00-4f50-11e9-903e-90a1f9549920.png)

**For more details**

**Comment by fetching** [comment]
@sagar-viradiya  I just merged https://github.com/Droidcon-Boston/conference-app-android/pull/196 to hopefully fix this crash. Can you take a new build with this fix and confirm you no longer see the crash but you do see the dancing Android when you visit Agenda?  Thanks!

**Comment by sagar-viradiya** [comment]
@fetching Sure will check and let you know.

**Comment by sagar-viradiya** [comment]
@fetching Seems like bug is gone now 👍

**Comment by fetching** [comment]
Awesome @sagar-viradiya thanks for verifying!
