### ISSUE TITLE
Crash when clicking on time rows in agenda

### ISSUE THREAD

**Issue by asfalcone** [Droidcon-Boston/conference-app-android#20]
```
AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mentalmachines.droidcon_boston, PID: 13120
       java.lang.ClassCastException: com.mentalmachines.droidcon_boston.views.agenda.ScheduleAdapterItemHeader cannot be cast to com.mentalmachines.droidcon_boston.views.agenda.ScheduleAdapterItem
           at com.mentalmachines.droidcon_boston.views.agenda.AgendaDayFragment.lambda$setupHeaderAdapter$1(AgendaDayFragment.java:116)
           at com.mentalmachines.droidcon_boston.views.agenda.AgendaDayFragment$$Lambda$2.onItemClick(Unknown Source)
           at eu.davidea.viewholders.FlexibleViewHolder.onClick(FlexibleViewHolder.java:121)
           at android.view.View.performClick(View.java:5637)
           at android.view.View$PerformClick.run(View.java:22429)
           at android.os.Handler.handleCallback(Handler.java:751)
           at android.os.Handler.dispatchMessage(Handler.java:95)
           at android.os.Looper.loop(Looper.java:154)
           at android.app.ActivityThread.main(ActivityThread.java:6121)
           at java.lang.reflect.Method.invoke(Native Method)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by kenyee** [comment]
fixed...needed to make sure it was an instance of the session instead of the time header
